#image: maven:latest

stages:
  - build
  - test
  - package

build:
  stage: build
  tags:
    - docker-atp
  script:
    - echo "Compiling the code..."
#    - mvn compile

test:
  stage: test
  tags:
    - docker-atp
  script:
    - echo "Testing the code..."
#    - mvn test

package:
  stage: package
  tags:
    - docker-atp
#  variables:
#    SKIP_TEST: "true"
  script:
    - echo "Packaging the code..."
#    - mvn package -DskipTests=${SKIP_TEST}
#  artifacts:
#    paths:
#      - target/*.jar
